[package]
name = "reflection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinybmp = "0.4"
embedded-graphics = "0.7"
embedded-layout = "0.2.0"
uefi = "0.18"
uefi-services = "0.15"